services:
  - type: web
    name: jtrack-api
    runtime: docker
    dockerContext: .
    dockerfilePath: ./docker/Dockerfile.api
    dockerCommand: sh -c "export API_PORT=${PORT}; PRISMA_BIN=$(find ./node_modules/.pnpm -maxdepth 2 -path '*/node_modules/prisma/build/index.js' | head -n 1); node \"$PRISMA_BIN\" migrate deploy --schema apps/api/prisma/schema.prisma && node apps/api/dist/src/main.js"
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jtrack-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_TTL
        value: 15m
      - key: JWT_REFRESH_TTL
        value: 30d
      - key: JWT_INVITE_SECRET
        sync: false
      - key: JWT_INVITE_TTL
        value: 7d
      - key: JWT_ISSUER
        value: jtrack-api
      - key: JWT_AUDIENCE
        value: jtrack
      - key: COOKIE_SECURE
        value: "true"
      - key: WEB_ORIGIN
        sync: false
      - key: UPLOAD_DIR
        value: ./uploads
      - key: STORAGE_PROVIDER
        value: local
      - key: MAIL_PROVIDER
        value: resend
      - key: MAIL_FROM
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: AUTH_VERIFY_EMAIL_TTL_MINUTES
        value: "15"
      - key: AUTH_RESET_PASSWORD_TTL_MINUTES
        value: "15"

databases:
  - name: jtrack-db
    plan: free
    databaseName: jtrack
    user: jtrack
